"""Predictive Alert model — stores trend-based predictive warnings.

Generated by PredictiveAnalytics service when a metric trend
projects a threshold breach within a configurable time window.
"""
from __future__ import annotations

from datetime import datetime

from sqlalchemy import Float, ForeignKey, Integer, String, Text, func
from sqlalchemy.orm import Mapped, mapped_column

from models.base import Base


class SanekPredictiveAlert(Base):
    __tablename__ = "sanek_predictive_alerts"

    id: Mapped[int] = mapped_column(primary_key=True)
    device_id: Mapped[int] = mapped_column(Integer, ForeignKey("devices.id"))
    site_id: Mapped[int | None] = mapped_column(Integer, ForeignKey("sites.id"), default=None)
    metric_name: Mapped[str] = mapped_column(String(50))
    current_value: Mapped[float] = mapped_column(Float)
    predicted_value: Mapped[float] = mapped_column(Float)
    threshold_value: Mapped[float] = mapped_column(Float)
    time_to_breach_min: Mapped[float] = mapped_column(Float)
    trend_slope: Mapped[float] = mapped_column(Float)
    r_squared: Mapped[float] = mapped_column(Float)
    severity: Mapped[str] = mapped_column(String(20), default="warning")
    status: Mapped[str] = mapped_column(String(20), default="active")
    message: Mapped[str | None] = mapped_column(Text, default=None)
    created_at: Mapped[datetime] = mapped_column(server_default=func.now())
