"""add_maintenance_alerts

Revision ID: 2d71b0f4423b
Revises: 51c0cc7ef80d
Create Date: 2026-02-17 13:03:39.324692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d71b0f4423b'
down_revision: Union[str, None] = '51c0cc7ef80d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('interval_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('info', 'warning', 'critical', 'overdue', name='alertseverity'), nullable=False),
    sa.Column('status', sa.Enum('active', 'acknowledged', 'resolved', name='alertstatus'), nullable=False),
    sa.Column('engine_hours', sa.Float(), nullable=False),
    sa.Column('hours_remaining', sa.Float(), nullable=False),
    sa.Column('interval_name', sa.String(length=50), nullable=False),
    sa.Column('interval_hours', sa.Integer(), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=False),
    sa.Column('site_code', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=100), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_maintenance_alerts_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interval_id'], ['maintenance_intervals.id'], name=op.f('fk_maintenance_alerts_interval_id_maintenance_intervals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_alerts')),
    sa.UniqueConstraint('device_id', 'interval_id', 'status', name='uq_maintenance_alerts_device_interval_status')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_alerts')
    # ### end Alembic commands ###
