"""add_maintenance_models

Revision ID: 51c0cc7ef80d
Revises: bfbd137c4e15
Create Date: 2026-02-17 12:37:37.554155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c0cc7ef80d'
down_revision: Union[str, None] = 'bfbd137c4e15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maintenance_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_templates'))
    )
    op.create_table('maintenance_intervals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('hours', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['maintenance_templates.id'], name=op.f('fk_maintenance_intervals_template_id_maintenance_templates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_intervals'))
    )
    op.create_table('maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('interval_id', sa.Integer(), nullable=True),
    sa.Column('performed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('engine_hours', sa.Float(), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('total_count', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('performed_by', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], name=op.f('fk_maintenance_logs_device_id_devices'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['interval_id'], ['maintenance_intervals.id'], name=op.f('fk_maintenance_logs_interval_id_maintenance_intervals'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_logs'))
    )
    op.create_table('maintenance_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interval_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=500), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interval_id'], ['maintenance_intervals.id'], name=op.f('fk_maintenance_tasks_interval_id_maintenance_intervals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_tasks'))
    )
    op.create_table('maintenance_log_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('log_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('task_text', sa.String(length=500), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['maintenance_logs.id'], name=op.f('fk_maintenance_log_items_log_id_maintenance_logs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['maintenance_tasks.id'], name=op.f('fk_maintenance_log_items_task_id_maintenance_tasks'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_log_items'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maintenance_log_items')
    op.drop_table('maintenance_tasks')
    op.drop_table('maintenance_logs')
    op.drop_table('maintenance_intervals')
    op.drop_table('maintenance_templates')
    # ### end Alembic commands ###
